### ISSUE TITLE
Name of the package

### ISSUE THREAD

**Issue by copy** [vincent-hugot/iTeML#42]
As it currently stands, this library has three names:

- The github project is named iTeML
- The opam package is named qtest
- The ocamlfind package is named qcheck

I think these should be unified under a single name to avoid confusion (especially for newcomers).

**Comment by vincent-hugot** [comment]
I think you're right. 

I at some point wanted to rename everything to iteml, because it's a nice acronym and (mainly) because it's unused elsewhere and thus immensely more searchable than "qtest". Everyone and their aunt's second cousin's mother have some piece of software matching "qtest" in a search, it seems. This one is not even in the 5 first Google search pages.

Unfortunately it started out under that name, so it's difficult to change it now. I would have cut the gordian knot by naming the new-and-improved, compatibility-breaking-but-so-awesome-everyone-would-want-to-switch new version iTeML and leaving the old version as qtest.

Of course, the shiny new version never came.

Still, I think it would be a good thing to rename. Possibly not as iTeML -- that's the best I could come up with, but I'm double-plus-ungood at naming things -- but something that fits the same bill of uniqueness.

Having said that, I now gleefully leave such conundrums in the hands of the current maintainer.

**Comment by c-cube** [comment]
Well, I agree the current state of things is sorry. For a start, I should have kept `qcheck` a separate lib and have added it as a regular dependency for qtest. It might still be time to revert this decision and move the random testing part to the `qcheck` repository again. As for the name of this project, I prefer `qtest` (never had a problem googling it, especially on opam ;), which is also the name of the tool and the one used in batteries.

**Comment by c-cube** [comment]
I am in the process of moving back the random testing into `qcheck` (as it was, and is still, confusing to many users). I will shortly remove it from qtest and just rely on a dependency for the generated code.

**Comment by UnixJunkie** [comment]
qtest and qheck for those two different things are good names. I always disliked this iTeML name.

**Comment by c-cube** [comment]
Taking another look at this issue:

- [x] qcheck is now a separate library
- `qtest ocaml` on google gives me this repository as first result
- I still dislike the "iteml" name (mostly because it doesn't tell us it's about testing)

So, I think we'll continue to have this named as `qtest` on opam and ocamlfind. if @vincent-hugot wants the rename the repository to `qtest` it's even better but it's probably not very important.

**Comment by vincent-hugot** [comment]
Note that renaming broke md5 for opam.

**Comment by c-cube** [comment]
Right. I will make a new release soon anyway, with the fix to #49.
